import { Injectable } from '@nestjs/common';
import { sql } from 'drizzle-orm';
import ExcelJS from 'exceljs';
import { METRIC_REGISTRY, PERMISSIONS, type PermissionKey } from '@vyuha/shared';

import { AppError } from '../../platform/common/errors.js';
import { AuditService } from '../../platform/audit/audit.service.js';
import { InjectDatabase, type Database } from '../../platform/db/db.provider.js';
import { hasPermission, type Principal } from '../../platform/rbac/principal.js';
import { CreditControlService } from './credit-control.service.js';
import { DataQualityService } from './data-quality.service.js';
import { DeskService } from './desk.service.js';
import { ExceptionsService } from './exceptions.service.js';
import { PenetrationService } from './penetration.service.js';
import { SalesAnalysisService, type SalesScope } from './sales-analysis.service.js';
import { TeamService } from './team.service.js';
import { TierService } from './tier.service.js';

/**
 * Export from the view (brief R6, O6): exactly what is on screen, as a
 * workbook -- a data sheet per table, and an About sheet carrying the
 * standard header block: company, report, period, filters, data as of,
 * the definitions' versions, generated by, generated at. Every export is
 * logged (K3); a viewer exports only what their own keys would show them,
 * because each report is re-read under their principal.
 */

export const EXPORT_REPORTS = [
  'league',
  'credit',
  'work-lists',
  'desk',
  'exceptions',
  'penetration',
  'class-grade',
  'data-quality',
  'sales-analysis',
] as const;
export type ExportReport = (typeof EXPORT_REPORTS)[number];

export interface ExportParams {
  readonly from: string;
  readonly to: string;
  readonly scope?: SalesScope;
}

interface Sheet {
  readonly name: string;
  readonly columns: readonly string[];
  readonly rows: readonly (string | number | null)[][];
}

const REPORT_META: Record<ExportReport, { title: string; permission: PermissionKey; metrics: readonly string[] }> = {
  league: { title: 'League table', permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['R05', 'D10'] },
  credit: { title: 'Credit control', permission: PERMISSIONS.CFO_RECEIVABLES_VIEW, metrics: ['D02', 'D04', 'D05', 'D06', 'D07', 'D17'] },
  'work-lists': { title: 'Work lists', permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['D10', 'D11', 'C12', 'C13'] },
  desk: { title: "Director's desk", permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['X02'] },
  exceptions: { title: 'Exceptions', permission: PERMISSIONS.CFO_EXCEPTIONS_VIEW, metrics: [] },
  penetration: { title: 'Penetration grid', permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['R05'] },
  'class-grade': { title: 'Class and payment grade', permission: PERMISSIONS.CFO_RECEIVABLES_VIEW, metrics: ['D18'] },
  'data-quality': { title: 'Data quality', permission: PERMISSIONS.CFO_EXCEPTIONS_VIEW, metrics: ['Q01'] },
  'sales-analysis': { title: 'Sales analysis', permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['R05', 'R07', 'R11', 'C01'] },
};

@Injectable()
export class CfoExportService {
  constructor(
    @InjectDatabase() private readonly db: Database,
    private readonly audit: AuditService,
    private readonly credit: CreditControlService,
    private readonly team: TeamService,
    private readonly desk: DeskService,
    private readonly exceptions: ExceptionsService,
    private readonly penetration: PenetrationService,
    private readonly tiers: TierService,
    private readonly quality: DataQualityService,
    private readonly sales: SalesAnalysisService,
  ) {}

  async build(principal: Principal, report: ExportReport, params: ExportParams): Promise<{ filename: string; buffer: Buffer }> {
    const meta = REPORT_META[report];
    if (!hasPermission(principal, meta.permission)) throw AppError.forbidden(`Exporting ${meta.title} needs ${meta.permission}.`);
    const sheets = await this.sheetsOf(principal, report, params);
    const org = await this.db.execute<{ name: string }>(sql`SELECT name FROM organizations WHERE id = ${principal.orgId} LIMIT 1`);
    const user = await this.db.execute<{ email: string }>(sql`SELECT email FROM users WHERE id = ${principal.userId} LIMIT 1`);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = org.rows[0]?.name ?? 'Vyuha';
    workbook.created = new Date();
    for (const sheet of sheets) {
      const ws = workbook.addWorksheet(sheet.name.replace(/[\\/?*[\]:]/gu, '-').slice(0, 31));
      const header = ws.addRow([...sheet.columns]);
      header.font = { bold: true };
      header.eachCell((cell) => {
        cell.border = { bottom: { style: 'thin' } };
      });
      for (const row of sheet.rows) ws.addRow([...row]);
      ws.columns.forEach((column, index) => {
        const widest = Math.max(sheet.columns[index]?.length ?? 8, ...sheet.rows.map((r) => String(r[index] ?? '').length));
        column.width = Math.min(48, Math.max(10, widest + 2));
      });
      ws.views = [{ state: 'frozen', ySplit: 1 }];
    }
    // R6: the header block, on its own sheet so the data sheet stays flat.
    const about = workbook.addWorksheet('About');
    const scope = params.scope ?? {};
    const filters = Object.entries(scope).filter(([, v]) => v !== undefined && v !== '').map(([k, v]) => `${k}=${String(v)}`).join('; ') || 'None';
    const definitions = meta.metrics.map((id) => METRIC_REGISTRY.find((m) => m.id === id)).filter((m) => m !== undefined).map((m) => `${m.id} ${m.label} v${String(m.version)} (${m.effectiveFrom})`).join('; ') || 'See the Definitions screen';
    const rows: [string, string][] = [
      ['Company', org.rows[0]?.name ?? ''],
      ['Report', meta.title],
      ['Period', `${params.from} to ${params.to}`],
      ['Comparison', 'Same days last year'],
      ['Filters', filters],
      ['Data as of', new Date().toISOString()],
      ['Definitions', definitions],
      ['Generated by', user.rows[0]?.email ?? principal.userId],
      ['Generated at', new Date().toISOString()],
    ];
    for (const [k, v] of rows) about.addRow([k, v]);
    about.getColumn(1).width = 16;
    about.getColumn(2).width = 80;
    about.getColumn(1).font = { bold: true };

    const buffer = Buffer.from(await workbook.xlsx.writeBuffer());
    await this.audit.write({
      orgId: principal.orgId,
      actorUserId: principal.userId,
      action: 'cfo.export',
      entityType: 'cfo_report',
      entityId: report,
      before: null,
      after: { report, from: params.from, to: params.to, filters, rows: sheets.reduce((n, s) => n + s.rows.length, 0) },
    });
    return { filename: `${meta.title.replace(/[^A-Za-z0-9]+/gu, '-')}-${params.from}-to-${params.to}.xlsx`, buffer };
  }

  private async sheetsOf(principal: Principal, report: ExportReport, params: ExportParams): Promise<Sheet[]> {
    const { from, to } = params;
    switch (report) {
      case 'league': {
        const rows = await this.team.league(principal, from, to);
        return [{ name: 'League', columns: ['Rank', 'Person', 'Book', 'Sales', 'Last year change', 'Collections', 'Overdue', 'Target', 'Achievement %'],
          rows: rows.map((r, i) => [i + 1, r.ownerEmail ?? r.ownerRef, r.bookSize, Number(r.sales), r.salesDelta.kind === 'pct' ? `${String(r.salesDelta.deltaPct)}%` : r.salesDelta.kind, Number(r.collections), Number(r.overdue), r.target === null ? null : Number(r.target), r.achievementPct]) }];
      }
      case 'credit': {
        const c = await this.credit.receivables(principal, from, to);
        return [
          { name: 'Summary', columns: ['Measure', 'Value'], rows: [['Outstanding', Number(c.outstanding)], ['Overdue', Number(c.overdue)], ['DSO countback', c.dsoCountback], ['Best possible DSO', c.bestPossibleDso], ['ADD', c.addDays], ['CEI', c.cei], ...Object.entries(c.buckets).map(([b, v]) => [`Bucket ${b}`, Number(v)] as [string, number])] },
          { name: 'Top overdue', columns: ['Party', 'Outstanding', 'Overdue', 'Oldest bill', 'Days overdue', 'Last payment', 'Delay cost per year'],
            rows: c.topOverdue.map((r) => [r.party, Number(r.outstanding), Number(r.overdue), r.oldestBill, r.daysOverdue, r.lastPayment, Number(r.costPerYear)]) },
        ];
      }
      case 'work-lists': {
        const lists = await this.credit.workLists(principal);
        return lists.lists.map((l) => ({ name: l.label, columns: ['Party', 'Amount', 'Reason'], rows: l.rows.map((r) => [r.party, Number(r.amount), r.reason]) }));
      }
      case 'desk': {
        const d = await this.desk.today(principal, { cap: 20, mixed: true });
        return [{ name: 'Desk', columns: ['Rank', 'Customer', 'Class', 'Owner', 'Primary reason', 'At stake', 'Score', 'Other reasons'],
          rows: d.rows.map((r) => [r.rank, r.party, r.tierCode, r.ownerLabel, r.primary.reason, Number(r.atStake), r.score, r.others.map((o) => o.reason).join(' | ')]) }];
      }
      case 'exceptions': {
        const e = await this.exceptions.list(principal, from, to);
        return e.checks.filter((c) => c.available).map((c) => ({ name: c.label, columns: ['Voucher', 'Type', 'Date', 'Party', 'Value', 'Why', 'Review', 'Review reason'],
          rows: c.rows.map((r) => [r.voucherNumber, r.voucherType, r.voucherDate, r.party, Number(r.amount), r.reason, r.review?.state ?? 'open', r.review?.reason ?? '']) }));
      }
      case 'penetration': {
        const p = await this.penetration.read(principal, from, to);
        const countRows = p.customers.map((c) => [c.party, ...p.categories.map((cat) => p.cells.find((x) => x.partyId === c.partyId && x.category === cat)?.count ?? 0)]);
        const valueRows = p.customers.map((c) => [c.party, ...p.categories.map((cat) => Number(p.cells.find((x) => x.partyId === c.partyId && x.category === cat)?.amount ?? 0))]);
        // Q2: both count and value grids, on separate sheets.
        return [
          { name: 'Count', columns: ['Customer', ...p.categories], rows: countRows },
          { name: 'Value', columns: ['Customer', ...p.categories], rows: valueRows },
        ];
      }
      case 'class-grade': {
        const g = await this.tiers.classGradeGrid(principal);
        return [
          { name: 'Count', columns: ['Class', ...g.grades], rows: g.classes.map((c) => [c, ...g.grades.map((gr) => g.cells.find((x) => x.tierCode === c && x.grade === gr)?.count ?? 0)]) },
          { name: 'Value', columns: ['Class', ...g.grades], rows: g.classes.map((c) => [c, ...g.grades.map((gr) => Number(g.cells.find((x) => x.tierCode === c && x.grade === gr)?.amount ?? 0))]) },
          { name: 'Customers', columns: ['Class', 'Grade', 'Customer', 'Outstanding'], rows: g.cells.flatMap((cell) => cell.parties.map((p) => [cell.tierCode, cell.grade, p.party, Number(p.outstanding)])) },
        ];
      }
      case 'data-quality': {
        const q = await this.quality.read(principal);
        return [{ name: 'Checks', columns: ['Check', 'Value', 'Unit', 'Target', 'Health', 'Fix', 'Note'],
          rows: q.checks.map((c) => [c.label, c.value, c.unit, c.target, c.health, c.fix, c.note ?? '']) }];
      }
      case 'sales-analysis': {
        const a = await this.sales.analyse(principal, from, to, params.scope ?? {});
        return [
          { name: 'Summary', columns: ['Measure', 'Value'], rows: [['Net sales', Number(a.summary.net)], ['Same days last year', Number(a.summary.lastYear)], ['Customers', a.summary.customers], ['Vouchers', a.summary.vouchers], ['Quantity', Number(a.summary.qty)], ['Unassigned', Number(a.summary.unassignedNet)]] },
          { name: 'By day', columns: ['Day', 'Net', 'Last year'], rows: a.trend.map((t) => [t.t, t.net, t.lastYear]) },
          ...a.breakdowns.map((b) => ({ name: `By ${b.label}`, columns: ['Name', 'Net', 'Last year', 'Qty', 'Vouchers'], rows: b.rows.map((r) => [r.label, Number(r.net), Number(r.lastYear), Number(r.qty), r.vouchers]) })),
        ];
      }
      default:
        throw AppError.notFound('report', String(report));
    }
  }
}
