import { Injectable } from '@nestjs/common';
import { sql } from 'drizzle-orm';
import ExcelJS from 'exceljs';
import { METRIC_REGISTRY, PERMISSIONS, type PermissionKey } from '@vyuha/shared';

import { AppError } from '../../platform/common/errors.js';
import { AnalyticsService } from './analytics.service.js';
import { AuditService } from '../../platform/audit/audit.service.js';
import { InjectDatabase, type Database } from '../../platform/db/db.provider.js';
import { hasPermission, type Principal } from '../../platform/rbac/principal.js';
import { BrandService } from './brand.service.js';
import { CreditControlService } from './credit-control.service.js';
import { DataQualityService } from './data-quality.service.js';
import { DeskService } from './desk.service.js';
import { PurchasesService } from './purchases.service.js';
import { ExceptionsService } from './exceptions.service.js';
import { PenetrationService } from './penetration.service.js';
import { MarginService } from './margin.service.js';
import { SalesAnalysisService, type SalesScope } from './sales-analysis.service.js';
import { TeamService } from './team.service.js';
import { TierService } from './tier.service.js';

/**
 * Export from the view (brief R6, O6): exactly what is on screen, as a
 * workbook -- a data sheet per table, and an About sheet carrying the
 * standard header block: company, report, period, filters, data as of,
 * the definitions' versions, generated by, generated at. Every export is
 * logged (K3); a viewer exports only what their own keys would show them,
 * because each report is re-read under their principal.
 */

export const EXPORT_REPORTS = [
  'league',
  'credit',
  'work-lists',
  'desk',
  'exceptions',
  'penetration',
  'class-grade',
  'data-quality',
  'sales-analysis',
  'margin',
  'brands',
  'analytics',
  'purchases',
] as const;
export type ExportReport = (typeof EXPORT_REPORTS)[number];

export interface ExportParams {
  readonly from: string;
  readonly to: string;
  readonly scope?: SalesScope;
}

interface Sheet {
  readonly name: string;
  readonly columns: readonly string[];
  readonly rows: readonly (string | number | null)[][];
}

const REPORT_BLURBS: Record<ExportReport, string> = {
  league: 'Every book priced the same way, with targets',
  credit: 'The receivable book as its measures, and the top overdue',
  'work-lists': 'Who to call, for how much, and why -- every list',
  desk: "Today's ranked call list with scores and reasons",
  exceptions: 'The vouchers that look wrong, with reviews',
  penetration: 'Customer by category: count and value grids',
  'class-grade': 'Class against payment grade, with the names',
  'data-quality': 'Every check, its value, target and fix',
  'sales-analysis': 'Summary, day trend and every breakdown',
  margin: 'The pocket-price waterfall, slices and below-cost grains',
  brands: 'Each principal with slabs and achievement',
  analytics: 'Price bands, ABC-XYZ, cohorts and concentration',
  purchases: 'Purchases by vendor, the payable book and the cash cycle',
};

const REPORT_META: Record<ExportReport, { title: string; permission: PermissionKey; metrics: readonly string[] }> = {
  league: { title: 'League table', permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['R05', 'D10'] },
  credit: { title: 'Credit control', permission: PERMISSIONS.CFO_RECEIVABLES_VIEW, metrics: ['D02', 'D04', 'D05', 'D06', 'D07', 'D17'] },
  'work-lists': { title: 'Work lists', permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['D10', 'D11', 'C12', 'C13'] },
  desk: { title: "Director's desk", permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['X02'] },
  exceptions: { title: 'Exceptions', permission: PERMISSIONS.CFO_EXCEPTIONS_VIEW, metrics: [] },
  penetration: { title: 'Penetration grid', permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['R05'] },
  'class-grade': { title: 'Class and payment grade', permission: PERMISSIONS.CFO_RECEIVABLES_VIEW, metrics: ['D18'] },
  'data-quality': { title: 'Data quality', permission: PERMISSIONS.CFO_EXCEPTIONS_VIEW, metrics: ['Q01'] },
  'sales-analysis': { title: 'Sales analysis', permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['R05', 'R07', 'R11', 'C01'] },
  margin: { title: 'Margin', permission: PERMISSIONS.CFO_MARGIN_VIEW, metrics: ['M05', 'M06', 'M07', 'M13'] },
  brands: { title: 'Brand performance', permission: PERMISSIONS.CFO_BRAND_VIEW, metrics: ['R05', 'M07'] },
  analytics: { title: 'Analytics', permission: PERMISSIONS.CFO_SALES_VIEW, metrics: ['M10', 'M11', 'C10', 'C11'] },  purchases: { title: 'Purchases', permission: PERMISSIONS.CFO_RECEIVABLES_VIEW, metrics: [] },
};

@Injectable()
export class CfoExportService {
  constructor(
    @InjectDatabase() private readonly db: Database,
    private readonly audit: AuditService,
    private readonly credit: CreditControlService,
    private readonly team: TeamService,
    private readonly desk: DeskService,
    private readonly purchases: PurchasesService,
    private readonly exceptions: ExceptionsService,
    private readonly penetration: PenetrationService,
    private readonly tiers: TierService,
    private readonly quality: DataQualityService,
    private readonly sales: SalesAnalysisService,
    private readonly marginService: MarginService,
    private readonly brandService: BrandService,
    private readonly analytics: AnalyticsService,
  ) {}

  async listSchedules(principal: Principal): Promise<{ id: string; report: string; cadence: string; recipients: string; lastRunOn: string | null }[]> {
    const rows = await this.db.execute<{ id: string; report: string; cadence: string; recipients: string; lastRunOn: string | null }>(sql`
      SELECT id, report, cadence, recipients, last_run_on AS "lastRunOn" FROM cfo_report_schedules
      WHERE org_id = ${principal.orgId} ORDER BY report, cadence
    `);
    return rows.rows;
  }

  async saveSchedule(principal: Principal, body: { id?: string; report: ExportReport; cadence: string; recipients: string }): Promise<void> {
    if (!hasPermission(principal, REPORT_META[body.report].permission)) {
      throw AppError.forbidden(`Scheduling ${REPORT_META[body.report].title} needs ${REPORT_META[body.report].permission}.`);
    }
    if (body.id !== undefined) {
      const updated = await this.db.execute<{ id: string }>(sql`
        UPDATE cfo_report_schedules SET report = ${body.report}, cadence = ${body.cadence}, recipients = ${body.recipients}
        WHERE org_id = ${principal.orgId} AND id = ${body.id} RETURNING id
      `);
      if (updated.rows[0] === undefined) throw AppError.notFound('schedule', body.id);
    } else {
      await this.db.execute(sql`
        INSERT INTO cfo_report_schedules (org_id, report, cadence, recipients, created_by)
        VALUES (${principal.orgId}, ${body.report}, ${body.cadence}, ${body.recipients}, ${principal.userId})
      `);
    }
    await this.audit.write({
      orgId: principal.orgId,
      actorUserId: principal.userId,
      action: 'cfo.schedule.saved',
      entityType: 'cfo_report_schedule',
      entityId: body.report,
      before: null,
      after: { report: body.report, cadence: body.cadence, recipients: body.recipients },
    });
  }

  async deleteSchedule(principal: Principal, id: string): Promise<void> {
    const gone = await this.db.execute<{ id: string }>(sql`
      DELETE FROM cfo_report_schedules WHERE org_id = ${principal.orgId} AND id = ${id} RETURNING id
    `);
    if (gone.rows[0] === undefined) throw AppError.notFound('schedule', id);
    await this.audit.write({ orgId: principal.orgId, actorUserId: principal.userId, action: 'cfo.schedule.deleted', entityType: 'cfo_report_schedule', entityId: id, before: null, after: null });
  }

  catalogue(principal: Principal): { report: ExportReport; title: string; blurb: string }[] {
    return EXPORT_REPORTS.filter((r) => hasPermission(principal, REPORT_META[r].permission)).map((r) => ({
      report: r,
      title: REPORT_META[r].title,
      blurb: REPORT_BLURBS[r],
    }));
  }

  async build(principal: Principal, report: ExportReport, params: ExportParams): Promise<{ filename: string; buffer: Buffer }> {
    const meta = REPORT_META[report];
    if (!hasPermission(principal, meta.permission)) throw AppError.forbidden(`Exporting ${meta.title} needs ${meta.permission}.`);
    const sheets = await this.sheetsOf(principal, report, params);
    const org = await this.db.execute<{ name: string }>(sql`SELECT name FROM organizations WHERE id = ${principal.orgId} LIMIT 1`);
    const user = await this.db.execute<{ email: string }>(sql`SELECT email FROM users WHERE id = ${principal.userId} LIMIT 1`);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = org.rows[0]?.name ?? 'Vyuha';
    workbook.created = new Date();
    for (const sheet of sheets) {
      const ws = workbook.addWorksheet(sheet.name.replace(/[\\/?*[\]:]/gu, '-').slice(0, 31));
      const header = ws.addRow([...sheet.columns]);
      header.font = { bold: true };
      header.eachCell((cell) => {
        cell.border = { bottom: { style: 'thin' } };
      });
      for (const row of sheet.rows) ws.addRow([...row]);
      ws.columns.forEach((column, index) => {
        const widest = Math.max(sheet.columns[index]?.length ?? 8, ...sheet.rows.map((r) => String(r[index] ?? '').length));
        column.width = Math.min(48, Math.max(10, widest + 2));
      });
      ws.views = [{ state: 'frozen', ySplit: 1 }];
    }
    // R6: the header block, on its own sheet so the data sheet stays flat.
    const about = workbook.addWorksheet('About');
    const scope = params.scope ?? {};
    const filters = Object.entries(scope).filter(([, v]) => v !== undefined && v !== '').map(([k, v]) => `${k}=${String(v)}`).join('; ') || 'None';
    const definitions = meta.metrics.map((id) => METRIC_REGISTRY.find((m) => m.id === id)).filter((m) => m !== undefined).map((m) => `${m.id} ${m.label} v${String(m.version)} (${m.effectiveFrom})`).join('; ') || 'See the Definitions screen';
    const rows: [string, string][] = [
      ['Company', org.rows[0]?.name ?? ''],
      ['Report', meta.title],
      ['Period', `${params.from} to ${params.to}`],
      ['Comparison', 'Same days last year'],
      ['Filters', filters],
      ['Data as of', new Date().toISOString()],
      ['Definitions', definitions],
      ['Generated by', user.rows[0]?.email ?? principal.userId],
      ['Generated at', new Date().toISOString()],
    ];
    for (const [k, v] of rows) about.addRow([k, v]);
    about.getColumn(1).width = 16;
    about.getColumn(2).width = 80;
    about.getColumn(1).font = { bold: true };

    const buffer = Buffer.from(await workbook.xlsx.writeBuffer());
    await this.audit.write({
      orgId: principal.orgId,
      actorUserId: principal.userId,
      action: 'cfo.export',
      entityType: 'cfo_report',
      entityId: report,
      before: null,
      after: { report, from: params.from, to: params.to, filters, rows: sheets.reduce((n, s) => n + s.rows.length, 0) },
    });
    return { filename: `${meta.title.replace(/[^A-Za-z0-9]+/gu, '-')}-${params.from}-to-${params.to}.xlsx`, buffer };
  }

  private async sheetsOf(principal: Principal, report: ExportReport, params: ExportParams): Promise<Sheet[]> {
    const { from, to } = params;
    switch (report) {
      case 'purchases': {
        const pr = await this.purchases.read(principal, from, to);
        return [
          { name: 'Summary', columns: ['Measure', 'Value'], rows: [
            ['Purchases', Number(pr.purchases.net)], ['Same days last year', Number(pr.purchases.lastYear)],
            ['Vouchers', pr.purchases.vouchers], ['Vendors', pr.purchases.vendors],
            ['Payables (running book)', Number(pr.payables.total)],
            ['DSO days', pr.cycle.dsoDays], ['DIO days', pr.cycle.dioDays], ['DPO days', pr.cycle.dpoDays], ['Cash cycle days', pr.cycle.cccDays],
            ...pr.cycle.notes.map((n) => ['Note', n] as [string, string]),
          ] },
          { name: 'By vendor', columns: ['Vendor', 'Purchases', 'Same days LY', 'Share %'],
            rows: pr.byVendor.map((r) => [r.vendor, Number(r.net), Number(r.lastYear), r.sharePct]) },
          { name: 'Payables', columns: ['Vendor', 'Payable'], rows: pr.payables.rows.map((r) => [r.vendor, Number(r.payable)]) },
          { name: 'Monthly', columns: ['Month', 'Purchases'], rows: pr.trend.map((r) => [r.month, Number(r.net)]) },
        ];
      }
      case 'league': {
        const rows = await this.team.league(principal, from, to);
        return [{ name: 'League', columns: ['Rank', 'Person', 'Book', 'Sales', 'Last year change', 'Collections', 'Overdue', 'Target', 'Achievement %'],
          rows: rows.map((r, i) => [i + 1, r.ownerEmail ?? r.ownerRef, r.bookSize, Number(r.sales), r.salesDelta.kind === 'pct' ? `${String(r.salesDelta.deltaPct)}%` : r.salesDelta.kind, Number(r.collections), Number(r.overdue), r.target === null ? null : Number(r.target), r.achievementPct]) }];
      }
      case 'credit': {
        const c = await this.credit.receivables(principal, from, to);
        return [
          { name: 'Summary', columns: ['Measure', 'Value'], rows: [['Outstanding', Number(c.outstanding)], ['Overdue', Number(c.overdue)], ['DSO countback', c.dsoCountback], ['Best possible DSO', c.bestPossibleDso], ['ADD', c.addDays], ['CEI', c.cei], ...Object.entries(c.buckets).map(([b, v]) => [`Bucket ${b}`, Number(v)] as [string, number])] },
          { name: 'Top overdue', columns: ['Party', 'Outstanding', 'Overdue', 'Oldest bill', 'Days overdue', 'Last payment', 'Delay cost per year'],
            rows: c.topOverdue.map((r) => [r.party, Number(r.outstanding), Number(r.overdue), r.oldestBill, r.daysOverdue, r.lastPayment, Number(r.costPerYear)]) },
        ];
      }
      case 'work-lists': {
        const lists = await this.credit.workLists(principal);
        return lists.lists.map((l) => ({ name: l.label, columns: ['Party', 'Amount', 'Reason'], rows: l.rows.map((r) => [r.party, Number(r.amount), r.reason]) }));
      }
      case 'desk': {
        const d = await this.desk.today(principal, { cap: 20, mixed: true });
        return [{ name: 'Desk', columns: ['Rank', 'Customer', 'Class', 'Owner', 'Primary reason', 'At stake', 'Score', 'Other reasons'],
          rows: d.rows.map((r) => [r.rank, r.party, r.tierCode, r.ownerLabel, r.primary.reason, Number(r.atStake), r.score, r.others.map((o) => o.reason).join(' | ')]) }];
      }
      case 'exceptions': {
        const e = await this.exceptions.list(principal, from, to);
        return e.checks.filter((c) => c.available).map((c) => ({ name: c.label, columns: ['Voucher', 'Type', 'Date', 'Party', 'Value', 'Why', 'Review', 'Review reason'],
          rows: c.rows.map((r) => [r.voucherNumber, r.voucherType, r.voucherDate, r.party, Number(r.amount), r.reason, r.review?.state ?? 'open', r.review?.reason ?? '']) }));
      }
      case 'penetration': {
        const p = await this.penetration.read(principal, from, to);
        const countRows = p.customers.map((c) => [c.party, ...p.categories.map((cat) => p.cells.find((x) => x.partyId === c.partyId && x.category === cat)?.count ?? 0)]);
        const valueRows = p.customers.map((c) => [c.party, ...p.categories.map((cat) => Number(p.cells.find((x) => x.partyId === c.partyId && x.category === cat)?.amount ?? 0))]);
        // Q2: both count and value grids, on separate sheets.
        return [
          { name: 'Count', columns: ['Customer', ...p.categories], rows: countRows },
          { name: 'Value', columns: ['Customer', ...p.categories], rows: valueRows },
        ];
      }
      case 'class-grade': {
        const g = await this.tiers.classGradeGrid(principal);
        return [
          { name: 'Count', columns: ['Class', ...g.grades], rows: g.classes.map((c) => [c, ...g.grades.map((gr) => g.cells.find((x) => x.tierCode === c && x.grade === gr)?.count ?? 0)]) },
          { name: 'Value', columns: ['Class', ...g.grades], rows: g.classes.map((c) => [c, ...g.grades.map((gr) => Number(g.cells.find((x) => x.tierCode === c && x.grade === gr)?.amount ?? 0))]) },
          { name: 'Customers', columns: ['Class', 'Grade', 'Customer', 'Outstanding'], rows: g.cells.flatMap((cell) => cell.parties.map((p) => [cell.tierCode, cell.grade, p.party, Number(p.outstanding)])) },
        ];
      }
      case 'data-quality': {
        const q = await this.quality.read(principal);
        return [{ name: 'Checks', columns: ['Check', 'Value', 'Unit', 'Target', 'Health', 'Fix', 'Note'],
          rows: q.checks.map((c) => [c.label, c.value, c.unit, c.target, c.health, c.fix, c.note ?? '']) }];
      }
      case 'sales-analysis': {
        const a = await this.sales.analyse(principal, from, to, params.scope ?? {});
        return [
          { name: 'Summary', columns: ['Measure', 'Value'], rows: [['Net sales', Number(a.summary.net)], ['Same days last year', Number(a.summary.lastYear)], ['Customers', a.summary.customers], ['Vouchers', a.summary.vouchers], ['Quantity', Number(a.summary.qty)], ['Unassigned', Number(a.summary.unassignedNet)]] },
          { name: 'By day', columns: ['Day', 'Net', 'Last year'], rows: a.trend.map((t) => [t.t, t.net, t.lastYear]) },
          ...a.breakdowns.map((b) => ({ name: `By ${b.label}`, columns: ['Name', 'Net', 'Last year', 'Qty', 'Vouchers'], rows: b.rows.map((r) => [r.label, Number(r.net), Number(r.lastYear), Number(r.qty), r.vouchers]) })),
        ];
      }
      case 'analytics': {
        const [bands, abc, cohorts, conc] = await Promise.all([
          this.analytics.priceBands(principal, from, to),
          this.analytics.abcXyz(principal),
          this.analytics.cohorts(principal),
          this.analytics.concentration(principal),
        ]);
        return [
          { name: 'Price bands', columns: ['Item', 'Qty', 'Net', 'Min', 'P25', 'Median', 'P75', 'Max', 'Recoverable'],
            rows: bands.map((b) => [b.item, Number(b.qty), Number(b.net), Number(b.min), Number(b.p25), Number(b.median), Number(b.p75), Number(b.max), Number(b.recoverable)]) },
          { name: 'ABC-XYZ', columns: ['ABC', 'XYZ', 'Items', 'Net (12m)'], rows: abc.cells.map((c) => [c.abc, c.xyz, c.count, Number(c.net)]) },
          { name: 'Cohorts', columns: ['Cohort', 'Size', ...Array.from({ length: 13 }, (_, i) => `M+${String(i)}`)],
            rows: cohorts.map((c) => [c.cohort, c.size, ...c.retention]) },
          { name: 'Concentration', columns: ['Measure', 'Value'], rows: [['Top-5 %', conc.top5Pct], ['Top-10 %', conc.top10Pct], ['HHI', conc.hhi], ['Top-5 % (LY)', conc.top5PctLy], ['HHI (LY)', conc.hhiLy]] },
        ];
      }
      case 'brands': {
        const b = await this.brandService.read(principal, from, to);
        return [
          { name: 'Brands', columns: ['Brand', 'Net', 'Last year', 'Share %', 'Qty', 'Realisation', 'Margin', 'Margin %', 'Target', 'Achievement %'],
            rows: b.brands.map((r) => [r.brand, Number(r.net), Number(r.lastYear), r.sharePct, Number(r.qty), r.realisation === null ? null : Number(r.realisation), r.margin === null ? null : Number(r.margin), r.marginPct, r.target === null ? null : Number(r.target), r.achievementPct]) },
          { name: 'Slabs', columns: ['Brand', 'Slab', 'Threshold', 'Progress (FYTD)', 'Distance', 'Attained %', 'Days left', 'Reward'],
            rows: b.brands.flatMap((r) => r.slabs.map((slab) => [slab.brand, slab.label, Number(slab.threshold), Number(slab.progress), Number(slab.distance), slab.attainedPct, slab.daysLeft, slab.reward])) },
        ];
      }
      case 'margin': {
        const m = await this.marginService.read(principal, from, to, params.scope ?? {});
        return [
          { name: 'Waterfall', columns: ['Layer', 'Amount'], rows: m.waterfall.map((w) => [w.label, Number(w.amount)]) },
          ...m.slices.map((slice) => ({ name: `By ${slice.label}`, columns: ['Name', 'Net', 'Margin', 'Margin %'], rows: slice.rows.map((r) => [r.label, Number(r.net), r.margin === null ? null : Number(r.margin), r.marginPct]) })),
          { name: 'Negative grains', columns: ['Day', 'Customer', 'Item', 'Net', 'Margin'], rows: m.negativeGrains.map((g) => [g.day, g.party, g.item, Number(g.net), Number(g.margin)]) },
        ];
      }
      default:
        throw AppError.notFound('report', String(report));
    }
  }
}
